title: "Sibling Dex - Homebrewery Template"
description: " A repository for assets used in my homebrewery templates "
masthead_title: "Homebrewery Template"
github_username: sibling-dex
url: https://sibling-dex.github.io/homebrewery-templates/

minimal_mistakes_skin: default
search: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%d %B %Y"

include:
  - _pages
  - docs

collections:
  category:
    output: true

titles_from_headings:
  strip_title: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sibling Dex"
  avatar : "https://avatars.githubusercontent.com/u/190822778"
  bio    : "TTRPG enthusiast and CSS wizard"

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://dice.camp/@sibling-dex/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: false
      share: false
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
  # docs
  - scope:
      path: "docs"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
